- ************************************** `item`

CREATE TABLE `item`
(
 `id`      int NOT NULL AUTO_INCREMENT ,
 `name`    varchar(45) NOT NULL ,
 `pic_url` varchar(255) NOT NULL ,
 `set_id`  int NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`set_id`),
CONSTRAINT `FK_3` FOREIGN KEY `FK_1` (`set_id`) REFERENCES `sets` (`id`)
);

-- ************************************** `item2res`

CREATE TABLE `item2res`
(
 `id`      int NOT NULL AUTO_INCREMENT ,
 `item_id` int NOT NULL ,
 `res_id`  int NOT NULL ,
 `count`   int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`item_id`),
CONSTRAINT `FK_1` FOREIGN KEY `FK_1` (`item_id`) REFERENCES `item` (`id`),
KEY `FK_2` (`res_id`),
CONSTRAINT `FK_2` FOREIGN KEY `FK_2` (`res_id`) REFERENCES `ressources` (`id`)
);

-- ************************************** `ressources`

CREATE TABLE `ressources`
(
 `id`      int NOT NULL AUTO_INCREMENT ,
 `name`    varchar(45) NOT NULL ,
 `pic_url` varchar(255) NOT NULL ,

PRIMARY KEY (`id`)
);

-- ************************************** `sets`

CREATE TABLE `sets`
(
 `id`   int NOT NULL AUTO_INCREMENT ,
 `name` varchar(255) NOT NULL ,

PRIMARY KEY (`id`)
);

-- **************************** SqlDBM: MySQL ***************************
-- **** Generated by SqlDBM: dofus touch by pidaman21@googlemail.com ****



-- ************************************** `stats`

CREATE TABLE `stats`
(
 `id`                      int NOT NULL AUTO_INCREMENT ,
 `item_id`                 int NOT NULL ,
 `critical_hits`           varchar(45) NULL ,
 `ap`                      varchar(45) NULL ,
 `mp`                      varchar(45) NULL ,
 `range`                   varchar(45) NULL ,
 `summons`                 varchar(45) NULL ,
 `heals`                   varchar(45) NULL ,
 `agility`                 varchar(45) NULL ,
 `chance`                  varchar(45) NULL ,
 `intelligence`            varchar(45) NULL ,
 `strength`                varchar(45) NULL ,
 `vitality`                varchar(45) NULL ,
 `wisdom`                  varchar(45) NULL ,
 `power`                   varchar(45) NULL ,
 `initiative`              varchar(45) NULL ,
 `prospecting`             varchar(45) NULL ,
 `damage`                  varchar(45) NULL ,
 `neutral_damage`          varchar(45) NULL ,
 `water_damage`            varchar(45) NULL ,
 `fire_damage`             varchar(45) NULL ,
 `air_damage`              varchar(45) NULL ,
 `earth_damage`            varchar(45) NULL ,
 `critical_damage`         varchar(45) NULL ,
 `pushback_damage`         varchar(45) NULL ,
 `neutral_resistance`      varchar(45) NULL ,
 `air_resistance`          varchar(45) NULL ,
 `earth_resistance`        varchar(45) NULL ,
 `water_resistance`        varchar(45) NULL ,
 `fire_resistance`         varchar(45) NULL ,
 `pushback_resistance`     varchar(45) NULL ,
 `critical_resistance`     varchar(45) NULL ,
 `ap_reduction`            varchar(45) NULL ,
 `mp_reduction`            varchar(45) NULL ,
 `lock`                    varchar(45) NULL ,
 `dodge`                   varchar(45) NULL ,
 `mp_parry`                varchar(45) NULL ,
 `ap_parry`                varchar(45) NULL ,
 `air_resistance_per`      varchar(45) NULL ,
 `neutral_resistance_per`  varchar(45) NULL ,
 `earth_resistance_per`    varchar(45) NULL ,
 `water_resistance_per`    varchar(45) NULL ,
 `fire_resistance_per`     varchar(45) NULL ,
 `pushback_resistance_per` varchar(45) NULL ,
 `critical_resistance_per` varchar(45) NULL ,
 `critical_hits_per`       varchar(45) NULL ,
 `pods`                    varchar(45) NULL ,

PRIMARY KEY (`id`),
UNIQUE KEY `Unique_id` (`item_id`),
KEY `FK_1` (`item_id`),
CONSTRAINT `FK_4` FOREIGN KEY `FK_1` (`item_id`) REFERENCES `item` (`id`)
);
